### ISSUE TITLE
Profile page > left column issue

### ISSUE THREAD

**Issue by cfoellmann** [cfoellmann/github-wide#8]
The left column on the profile page is normally 25% wide but that does not translate to wide screen.
SEE screenshot: 
![2017-09-05](https://user-images.githubusercontent.com/1256090/30064834-3ff6c526-9253-11e7-94fe-557aa9a62f23.png)

We need something like:

```css
.page-profile .pr-3 {
    max-width: 253px;
}

.page-profile .pl-2 {
    width: auto !important;
}
```

but I currently dont have the time to debug. This looks good on the main page of the profile but destroys the repositories listing.
May someone is interested in doing this.
@hernandev @nickcampbell18
